version: '3.9'

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app
      - app-cluster
      - app-01
      - app-02
      - app-03
      - app-04
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: 8080
    ports:
      - "8080:8080"
    restart: always
    environment:
      - ARG_MODE=FORK
      - ARG_PORT=8080
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_TIME_MINUTES=${SESSION_TIME_MINUTES}
      - MONGO_URL=${MONGO_URL}

  app-cluster:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: 8081
    restart: always
    environment:
      - ARG_MODE=CLUSTER
      - ARG_PORT=8081
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_TIME_MINUTES=${SESSION_TIME_MINUTES}
      - MONGO_URL=${MONGO_URL}

  app-01:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: 8082
    restart: always
    environment:
      - ARG_MODE=FORK
      - ARG_PORT=8082
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_TIME_MINUTES=${SESSION_TIME_MINUTES}
      - MONGO_URL=${MONGO_URL}

  app-02:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: 8083
    restart: always
    environment:
      - ARG_MODE=FORK
      - ARG_PORT=8083
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_TIME_MINUTES=${SESSION_TIME_MINUTES}
      - MONGO_URL=${MONGO_URL}

  app-03:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: 8084
    restart: always
    environment:
      - ARG_MODE=FORK
      - ARG_PORT=8084
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_TIME_MINUTES=${SESSION_TIME_MINUTES}
      - MONGO_URL=${MONGO_URL}

  app-04:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PORT: 8085
    restart: always
    environment:
      - ARG_MODE=FORK
      - ARG_PORT=8085
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_TIME_MINUTES=${SESSION_TIME_MINUTES}
      - MONGO_URL=${MONGO_URL}
